server:
  port: 8000

spring:
  application:
    name: api-gateway
  redis:
    host: redis
    port: 6379
  cloud:
    gateway:
      routes:
        # SDS Services — controllers at /auth/*, /users/*, etc.
        # StripPrefix=1 removes only the leading /api segment.
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        # gRPC-origin Services — controllers already include /api/ prefix
        # (e.g. /api/accounts/**, /api/health-records/**) so no stripping needed.
        # user-grpc-service uses RewritePath to map /api/grpc-users/** → /api/users/**
        - id: user-grpc-service
          uri: lb://user-grpc-service
          predicates:
            - Path=/api/grpc-users/**
          filters:
            - RewritePath=/api/grpc-users/(?<remaining>.*), /api/users/$\{remaining}

        - id: financial-service
          uri: lb://financial-service
          predicates:
            - Path=/api/accounts/**,/api/transactions/**

        - id: health-service
          uri: lb://health-service
          predicates:
            - Path=/api/health-records/**,/api/vitals/**

        - id: social-service
          uri: lb://social-service
          predicates:
            - Path=/api/profiles/**,/api/posts/**,/api/connections/**

        # OpenAPI Documentation Routes
        - id: auth-service-api-docs
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/auth-service
          filters:
            - RewritePath=/v3/api-docs/auth-service, /v3/api-docs

        - id: user-service-api-docs
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/user-service
          filters:
            - RewritePath=/v3/api-docs/user-service, /v3/api-docs

        - id: order-service-api-docs
          uri: lb://order-service
          predicates:
            - Path=/v3/api-docs/order-service
          filters:
            - RewritePath=/v3/api-docs/order-service, /v3/api-docs

        - id: product-service-api-docs
          uri: lb://product-service
          predicates:
            - Path=/v3/api-docs/product-service
          filters:
            - RewritePath=/v3/api-docs/product-service, /v3/api-docs

        - id: user-grpc-service-api-docs
          uri: lb://user-grpc-service
          predicates:
            - Path=/v3/api-docs/user-grpc-service
          filters:
            - RewritePath=/v3/api-docs/user-grpc-service, /v3/api-docs

        - id: financial-service-api-docs
          uri: lb://financial-service
          predicates:
            - Path=/v3/api-docs/financial-service
          filters:
            - RewritePath=/v3/api-docs/financial-service, /v3/api-docs

        - id: health-service-api-docs
          uri: lb://health-service
          predicates:
            - Path=/v3/api-docs/health-service
          filters:
            - RewritePath=/v3/api-docs/health-service, /v3/api-docs

        - id: social-service-api-docs
          uri: lb://social-service
          predicates:
            - Path=/v3/api-docs/social-service
          filters:
            - RewritePath=/v3/api-docs/social-service, /v3/api-docs

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:4200"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidation12345678901234567890

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: auth-service
        url: /v3/api-docs/auth-service
      - name: user-service
        url: /v3/api-docs/user-service
      - name: order-service
        url: /v3/api-docs/order-service
      - name: product-service
        url: /v3/api-docs/product-service
      - name: user-grpc-service
        url: /v3/api-docs/user-grpc-service
      - name: financial-service
        url: /v3/api-docs/financial-service
      - name: health-service
        url: /v3/api-docs/health-service
      - name: social-service
        url: /v3/api-docs/social-service
