server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:orderdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8080

jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidation12345678901234567890

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
